name: yona_app
description: Aplicación de chat enfocado en la salud/deporte/dieta con IA.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0 #almacenamiento de mensajes
  cupertino_icons: ^1.0.5
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.1  # Autenticación
  cloud_firestore: ^5.4.4  # Guardado datos de usuarios
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    