// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgL5uEGLaDJ6dSzefzQn4fQMy4G-9hX1Y',
    appId: '1:117125632502:web:a4b636481e131ff9c477d7',
    messagingSenderId: '117125632502',
    projectId: 'yona-proyecto',
    authDomain: 'yona-proyecto.firebaseapp.com',
    storageBucket: 'yona-proyecto.firebasestorage.app',
    measurementId: 'G-NMFH5VX2S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPdsTJVDIabcdA7GQyFd5kTiAHOVePUU',
    appId: '1:117125632502:android:917cabc6a4a1ab90c477d7',
    messagingSenderId: '117125632502',
    projectId: 'yona-proyecto',
    storageBucket: 'yona-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFHG0a6T8VJT1rLYWQmygyeYJHgEtuOnI',
    appId: '1:117125632502:ios:a2a67ab4fa2aa4d4c477d7',
    messagingSenderId: '117125632502',
    projectId: 'yona-proyecto',
    storageBucket: 'yona-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.yonaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFHG0a6T8VJT1rLYWQmygyeYJHgEtuOnI',
    appId: '1:117125632502:ios:a2a67ab4fa2aa4d4c477d7',
    messagingSenderId: '117125632502',
    projectId: 'yona-proyecto',
    storageBucket: 'yona-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.yonaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgL5uEGLaDJ6dSzefzQn4fQMy4G-9hX1Y',
    appId: '1:117125632502:web:873ae1c09fe9650cc477d7',
    messagingSenderId: '117125632502',
    projectId: 'yona-proyecto',
    authDomain: 'yona-proyecto.firebaseapp.com',
    storageBucket: 'yona-proyecto.firebasestorage.app',
    measurementId: 'G-KS6GHGTP1E',
  );
}
